// These are large types that represent reponses from our api
export type Player = {
  id: number;
  name: string;
  position: 'C' | 'RW' | 'LW' | 'RD' | 'LD';
  league: number;
  team: string;
  season: number;
  gamesPlayed: number;
  timeOnIce: number;
  goals: number;
  assists: number;
  points: number;
  plusMinus: number;
  pim: number;
  ppGoals: number;
  ppAssists: number;
  ppPoints: number;
  ppTimeOnIce: number;
  shGoals: number;
  shAssists: number;
  shPoints: number;
  shTimeOnIce: number;
  fights: number;
  fightWins: number;
  fightLosses: number;
  faceoffs: number | undefined;
  faceoffWins: number | undefined;
  gwg: number | undefined;
  hits: number;
  giveaways: number;
  takeaways: number;
  shotsBlocked: number;
  shotsOnGoal: number;
  gameRating: number;
  offensiveGameRating: number;
  defensiveGameRating: number;
};

export type PlayerInfo = {
  height: number;
  id: number;
  league: number;
  season: number;
  weight: number;
  team: string;
  position: 'C' | 'LW' | 'RW' | 'LD' | 'RD';
};

export type PlayerWithAdvancedStats = Player & {
  advancedStats: {
    PDO: number;
    GF60: number;
    GA60: number;
    SF60: number;
    SA60: number;
    CF: number;
    CA: number;
    CFPct: number;
    CFPctRel: number;
    FF: number;
    FA: number;
    FFPct: number;
    FFPctRel: number;
  };
};

export type Goalie = {
  id: number;
  name: string;
  position: 'G';
  league: number;
  team: string;
  season: number;
  gamesPlayed: number;
  minutes: number;
  wins: number;
  losses: number;
  ot: number;
  shotsAgainst: number;
  saves: number;
  goalsAgainst: number;
  gaa: number;
  shutouts: number;
  savePct: number;
  gameRating: number;
};

export type GoalieInfo = {
  height: number;
  id: number;
  league: number;
  season: number;
  weight: number;
  team: string;
};

export type Team = {
  id: number;
  season: number;
  conference: number;
  division: number;
  name: string;
  nameDetails: { first: string; second: string };
  abbreviation: string;
  location: string;
  colors: { primary: string; secondary: string; text: string };
  stats: {
    wins: number;
    losses: number;
    overtimeLosses: number;
    shootoutWins: number;
    shootoutLosses: number;
    points: number;
    goalsFor: number;
    goalsAgainst: number;
    winPercent: number;
  };
};

export type PlayerRatings = {
  screening: number;
  gettingOpen: number;
  passing: number;
  puckhandling: number;
  shootingAccuracy: number;
  shootingRange: number;
  offensiveRead: number;
  checking: number;
  hitting: number;
  positioning: number;
  stickchecking: number;
  shotBlocking: number;
  faceoffs: number;
  defensiveRead: number;
  acceleration: number;
  agility: number;
  balance: number;
  speed: number;
  stamina: number;
  strength: number;
  fighting: number;
  aggression: number;
  bravery: number;
  appliedTPE?: number;
};

export type GoalieRatings = {
  blocker: number;
  glove: number;
  passing: number;
  pokeCheck: number;
  positioning: number;
  rebound: number;
  recovery: number;
  puckhandling: number;
  lowShots: number;
  reflexes: number;
  skating: number;
  mentalToughness: number;
  goalieStamina: number;
  appliedTPE?: number;
};

export type InternalPlayerRatings = {
  Name: string;
  Abbr: string;
  PlayerID: number;
  LeagueID: number;
  SeasonID: number;
  G: number;
  LD: number;
  RD: number;
  LW: number;
  C: number;
  RW: number;
  Aggression: number;
  Bravery: number;
  Determination: number;
  Teamplayer: number;
  Leadership: number;
  Temperament: number;
  Professionalism: number;
  MentalToughness: number;
  GoalieStamina: number;
  Acceleration: number;
  Agility: number;
  Balance: number;
  Speed: number;
  Stamina: number;
  Strength: number;
  Fighting: number;
  Screening: number;
  GettingOpen: number;
  Passing: number;
  PuckHandling: number;
  ShootingAccuracy: number;
  ShootingRange: number;
  OffensiveRead: number;
  Checking: number;
  Faceoffs: number;
  Hitting: number;
  Positioning: number;
  ShotBlocking: number;
  Stickchecking: number;
  DefensiveRead: number;
  GPositioning: number;
  GPassing: number;
  GPokecheck: number;
  Blocker: number;
  Glove: number;
  Rebound: number;
  Recovery: number;
  GPuckhandling: number;
  LowShots: number;
  GSkating: number;
  Reflexes: number;
  Skating: number;
  Shooting: number;
  Playmaking: number;
  Defending: number;
  Physicality: number;
  Conditioning: number;
  Character: number;
  HockeySense: number;
  GoalieTechnique: number;
  GoalieOverallPositioning: number;
};
